name: Main workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run Build
        run: gradle clean build --parallel
  pitest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run Pitest
        run: gradle clean pitest pitestReportAggregate --parallel
      - name: Publish Pitest Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/pitest
          exclude_assets: '.github,*.xml'
          full_commit_message: Publishing pitest reports for $GITHUB_SHA
